import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import type { UnlayerConfig } from "@unlayer-internal/shared-elements";
import { DEFAULT_CONFIG } from "@unlayer-internal/shared-elements";
import { htmlToPlainText } from "@unlayer-internal/shared-elements";
import type { RenderMode } from "@unlayer-internal/shared-elements";
import { extractHeadFromTree } from "./extract-head";

/**
 * Renders an Unlayer element tree to an HTML string.
 *
 * - Passes merged config via the `config` prop (no React context — works in Server Components)
 * - Uses `renderToStaticMarkup` — no React hydration markers, clean HTML for email/PDF
 * - Synchronous
 *
 * @param element - A React element tree (e.g. `<Body><Row>...</Row></Body>`)
 * @param config  - Optional config overrides (mode, cdnBaseUrl, etc.)
 * @returns Clean HTML string
 * @throws {Error} If rendering fails, with a helpful message
 *
 * @example
 * ```tsx
 * import { renderToHtml, Body, Row, Column, Paragraph } from "@unlayer/react-elements";
 *
 * const html = renderToHtml(
 *   <Body><Row><Column><Paragraph>Hello</Paragraph></Column></Row></Body>,
 *   { mode: "email", cdnBaseUrl: "https://my-cdn.com" }
 * );
 * ```
 */
export function renderToHtml(
  element: React.ReactElement,
  config?: Partial<UnlayerConfig>
): string {
  const mergedConfig = { ...DEFAULT_CONFIG, ...config };

  try {
    // Pass config via prop (not context) so this works in React Server Components.
    // Body reads `config` prop and threads it as `_config` to children via cloneElement.
    const enriched = React.cloneElement(element, { config: mergedConfig });
    return renderToStaticMarkup(enriched);
  } catch (error) {
    const message =
      error instanceof Error ? error.message : String(error);
    throw new Error(
      `[Unlayer] renderToHtml failed: ${message}\n` +
        `Tip: Ensure your tree uses Body > Row > Column > Item structure.`
    );
  }
}

/**
 * Renders an Unlayer element tree to a plain text string.
 *
 * Internally calls `renderToHtml` then converts to plain text using
 * `htmlToPlainText`. Useful for generating the text/plain MIME part
 * of multipart emails (critical for deliverability).
 *
 * @param element - A React element tree (e.g. `<Body><Row>...</Row></Body>`)
 * @param config  - Optional config overrides (mode, cdnBaseUrl, etc.)
 * @returns Plain text representation of the email
 *
 * @example
 * ```tsx
 * import { renderToPlainText, Body, Row, Column, Paragraph } from "@unlayer/react-elements";
 *
 * const text = renderToPlainText(
 *   <Body mode="email"><Row><Column><Paragraph>Hello World</Paragraph></Column></Row></Body>
 * );
 * // "Hello World"
 * ```
 */
export function renderToPlainText(
  element: React.ReactElement,
  config?: Partial<UnlayerConfig>
): string {
  const html = renderToHtml(element, config);
  return htmlToPlainText(html);
}

/**
 * Result of renderToHtmlParts — head and body as separate strings.
 */
export interface HtmlParts {
  /** `<head>` content: `<style>` blocks with component CSS, optional `<script>` tags */
  head: string;
  /** `<body>` content: the rendered HTML (same output as `renderToHtml`) */
  body: string;
}

/**
 * Renders an Unlayer element tree to separate head and body HTML strings.
 *
 * This is the recommended API for sending emails, because email clients need
 * the `<style>` block in `<head>` for hover effects, responsive breakpoints,
 * and font declarations that cannot be expressed as inline styles.
 *
 * - `head` contains `<style>` tags with CSS generated by each component's
 *   head function (button hover colors, body fonts, link styles, etc.)
 * - `body` is identical to what `renderToHtml()` returns
 *
 * @param element - A React element tree (e.g. `<Email><Row>...</Row></Email>`)
 * @param config  - Optional config overrides (mode, cdnBaseUrl, etc.)
 * @returns `{ head, body }` — drop these into your HTML document template
 *
 * @example
 * ```tsx
 * import { renderToHtmlParts, Email, Row, Column, Button } from "@unlayer/react-elements";
 *
 * const { head, body } = renderToHtmlParts(
 *   <Email>
 *     <Row><Column><Button>Click</Button></Column></Row>
 *   </Email>
 * );
 *
 * const html = `<!DOCTYPE html>
 * <html><head>${head}</head>${body}</html>`;
 * ```
 */
export function renderToHtmlParts(
  element: React.ReactElement,
  config?: Partial<UnlayerConfig>
): HtmlParts {
  // Render body HTML (same as renderToHtml)
  const body = renderToHtml(element, config);

  // Resolve display mode from config or element props
  const mergedConfig = { ...DEFAULT_CONFIG, ...config };
  const displayMode: RenderMode =
    (element.props as any).mode ?? mergedConfig.mode ?? "web";

  // Extract head CSS/JS/tags by walking the element tree
  const { css, js, tags } = extractHeadFromTree(element, {
    displayMode,
    headConfig: mergedConfig.headConfig,
  });

  // Build head string
  const headParts: string[] = [];

  if (css) {
    headParts.push(`<style>${css}</style>`);
  }

  if (js) {
    headParts.push(`<script>${js}</script>`);
  }

  if (tags.length > 0) {
    headParts.push(...tags);
  }

  return {
    head: headParts.join("\n"),
    body,
  };
}
